const apiEndPoint = {
  signup: "auth/signup",
  login: "auth/login",
  logout: "auth/logout",
  forgotpassword: "auth/forgot-password",
  resetpassword: "auth/reset-password",
  getprofile: "user/profile",
  updateprofile: "user/update",
  myscoreboard: "my-scoreboard",
  getRedeemPoints: "redeem-list",
  shippingDetails: "shipping-details",
  deleteAccount: "delete-account",
  signupQuestionaire: "user/signup-questionaire",
  getmymatches: "my-matches",
  getNotification: "notifications",
  clearNotification: "notification/all",
  home: "home",
  addMatches: "add-matches",
  getQuiz: "get-quiz",
  addQuiz: "store-quiz-answer",
  checkQuizMatchAction: "check-quiz-match",
  getNotficationCountData: "notification-count",
  getOtherUserProfile: "get-other-profile",
  resetNotificationCount: "reset-notification-count",
  webSubscription: "web-subscription",
  planType: "get/plan-type",
  cancelSubscription: "cancel-subscription",
};

export default apiEndPoint;
