// export const STRIPE_PUBLISHABLE_KEY = "pk_test_nL9qFElZB2O9GeSoSQ9FNtFO";
export const STRIPE_PUBLISHABLE_KEY =
  "pk_test_51MU5U3LymMYoSswY7RCzfwWYVz5wM71UDcmZwYI9OXdJzkIlkfY92Lw1n7MmffxcDZkUBHXUmMDSfDcmAAWDDtFi00sOypmYOI";
